# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.URLField()),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('decscription', models.TextField()),
            ],
        ),
    ]
