# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='project',
            name='main_index_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
