# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171117_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='URL',
        ),
    ]
