# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decscription',
            new_name='description',
        ),
    ]
