# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20171117_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(upload_to=b'', verbose_name='/static'),
        ),
    ]
