# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20171118_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(upload_to='static'),
        ),
    ]
