# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 22:40
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('portfolio', '0011_auto_20171218_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
