# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
    ]
