# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20171229_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'skill'},
        ),
    ]
